title: heimuru
description: in progressss
url: "https://heimuru.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "neon"

author:
  name: "Heidi Muurikainen"
  avatar: "/assets/images/heidi1.png"
  bio: "Exploring cybersecurity with a sharp eye for detail, a drive to learn, and a mindset built for systems and strategy."
  location: "Finland"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/heimuru"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/heidi-muurikainen"